
namespace Lexer;

/// <summary>
/// Represents the result of a lexer rule match operation.
/// This struct encapsulates information about whether a match was found,
/// the length of the matched text, whether the end of the file has been reached,
/// and the token generated by the rule.
/// </summary>
/// <typeparam name="TToken">The type of token produced by the lexer rule.</typeparam>
/// <remarks>
/// Initializes a new instance of the MatchResult struct.
/// </remarks>
/// <param name="isMatchFound">True if a match was found; otherwise, false.</param>
/// <param name="matchedTextLength">The length of the matched text.</param>
/// <param name="isEndOfFile">True if the end of the file has been reached; otherwise, false.</param>
/// <param name="generatedToken">The token generated by the rule, if a match was found; otherwise, null.</param>
public readonly struct MatchResult<TToken>(bool isMatchFound, int matchedTextLength, bool isEndOfFile, TToken generatedToken)
{
    /// <summary>
    /// Indicates whether a match was found by the LexerRule.Match method.
    /// </summary>
    public bool IsMatchFound { get; init; } = isMatchFound;

    /// <summary>
    /// The length of the matched text.
    /// </summary>
    public int MatchedTextLength { get; init; } = matchedTextLength;

    /// <summary>
    /// Indicates whether the end of the file has been reached.
    /// </summary>
    public bool IsEndOfFile { get; init; } = isEndOfFile;

    /// <summary>
    /// The token generated by the rule, if a match was found.
    /// </summary>
    public TToken GeneratedToken { get; init; } = generatedToken;
}

/// <summary>
/// Abstract base class for lexer rules.
/// </summary>
/// <typeparam name="TToken">The type of token produced by the lexer rule.</typeparam>
/// <remarks>
/// Initializes a new instance of the LexerRule class with the specified return behavior.
/// </remarks>
/// <param name="returnTokenOnMatch">True to return the token on match; false to skip the token.</param>
public abstract class LexerRule<TToken>(bool returnTokenOnMatch)
{
    /// <summary>
    /// Gets or sets a value indicating whether the lexer should return the token if a match is found.
    /// If true, the token is returned; if false, the token is skipped and the lexer looks for the next one.
    /// </summary>
    public bool ReturnTokenOnMatch { get; protected set; } = returnTokenOnMatch;

    /// <summary>
    /// Attempts to match the input text and produce a token.
    /// </summary>
    /// <param name="input">The input text to match.</param>
    /// <returns>
    /// A MatchResult containing information about whether a match was found,
    /// the length of the matched text, whether the end of the file has been reached,
    /// and the generated token if a match was found.
    /// </returns>
    public abstract MatchResult<TToken> Match(ReadOnlyMemory<char> input);
}